# Generated by Django 3.2 on 2022-01-31 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('request_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время запроса')),
            ],
            options={
                'verbose_name': 'геопозиция места',
                'verbose_name_plural': 'геопозиции мест',
            },
        ),
    ]
