# Generated by Django 3.2 on 2022-01-13 09:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_customer_order_orderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name='адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='fistname',
            field=models.CharField(blank=True, max_length=50, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='телефон'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
