# Generated by Django 3.2 on 2022-01-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20220113_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
