# Generated by Django 3.2 on 2022-01-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderproducts_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('НО', 'Необработан'), ('ГО', 'Готовится'), ('ГВ', 'Готов'), ('ДО', 'Доставляется'), ('ДН', 'Доставлен'), ('ОН', 'Отменен')], db_index=True, default='НО', max_length=2, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='адрес доставки'),
        ),
    ]
