# Generated by Django 3.2 on 2022-01-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220127_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('НО', 'Не определен'), ('НЛ', 'Наличными'), ('БК', 'Банковской картой'), ('ЭК', 'Электронный кошелек')], db_index=True, default='НО', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
