# Generated by Django 3.2 on 2022-02-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='call_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='call_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='когда позвонить'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Когда доставить'),
        ),
    ]
