# Generated by Django 3.2 on 2022-02-05 09:54

from django.db import migrations


class Migration(migrations.Migration):
    def set_order_products_price(apps, schema_editor):
        Product = apps.get_model("foodcartapp", "Product")
        OrderProducts = apps.get_model("foodcartapp", "OrderProducts")
        for orderproduct in OrderProducts.objects.all():
            orderproduct.price = Product.objects.get(pk=orderproduct.id).price

    dependencies = [
        ("foodcartapp", "0055_auto_20220204_1735"),
    ]

    operations = [
        migrations.RunPython(set_order_products_price),
    ]
