# Generated by Django 3.2 on 2022-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0056_auto_20220205_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                max_length=200, verbose_name="адрес доставки"
            ),
        ),
    ]
