# Generated by Django 3.2 on 2022-02-17 07:25

from django.db import migrations


class Migration(migrations.Migration):
    def set_order_products_price(apps, schema_editor):
        Product = apps.get_model("foodcartapp", "Product")
        OrderProducts = apps.get_model("foodcartapp", "OrderProducts")
        orderproducts_set = OrderProducts.objects.all()
        if orderproducts_set.exists():
            for orderproduct in orderproducts_set.iterator():
                orderproduct.price = Product.objects.get(
                    pk=orderproduct.id
                ).price

    dependencies = [
        ("foodcartapp", "0058_alter_order_address"),
    ]

    operations = [
        migrations.RunPython(set_order_products_price),
    ]
