# Generated by Django 3.2 on 2022-02-17 08:44

from django.db import migrations


class Migration(migrations.Migration):
    def set_order_products_price(apps, schema_editor):
        Product = apps.get_model("foodcartapp", "Product")
        OrderProducts = apps.get_model("foodcartapp", "OrderProducts")
        orderproducts_set = OrderProducts.objects.all()
        product_set = Product.objects.all()
        if orderproducts_set.exists():
            for orderproduct in orderproducts_set.iterator():
                orderproduct.price = product_set.objects.order_products.get(
                    product=orderproduct.product
                ).price

    dependencies = [
        ("foodcartapp", "0059_auto_20220217_1025"),
    ]

    operations = [
        migrations.RunPython(set_order_products_price),
    ]
